<?php


namespace Database\Seeders;

use App\Models\Team;
use Illuminate\Database\Seeder;

class team_seeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            // ----- África (54) -----
            'Algeria',
            'Angola',
            'Benin',
            'Botswana',
            'Burkina Faso',
            'Burundi',
            'Cabo Verde',
            'Cameroon',
            'Central African Republic',
            'Chad',
            'Comoros',
            'Congo',
            'Congo, Democratic Republic of the',
            'Côte d\'Ivoire',
            'Djibouti',
            'Egypt',
            'Equatorial Guinea',
            'Eritrea',
            'Eswatini',
            'Ethiopia',
            'Gabon',
            'Gambia',
            'Ghana',
            'Guinea',
            'Guinea-Bissau',
            'Kenya',
            'Lesotho',
            'Liberia',
            'Libya',
            'Madagascar',
            'Malawi',
            'Mali',
            'Mauritania',
            'Mauritius',
            'Morocco',
            'Mozambique',
            'Namibia',
            'Niger',
            'Nigeria',
            'Rwanda',
            'Sao Tome and Principe',
            'Senegal',
            'Seychelles',
            'Sierra Leone',
            'Somalia',
            'South Africa',
            'South Sudan',
            'Sudan',
            'Tanzania, United Republic of',
            'Togo',
            'Tunisia',
            'Uganda',
            'Zambia',
            'Zimbabwe',

            // ----- América del Norte (4) -----
            'Bermuda',
            'Canada',
            'Mexico',
            'United States of America',

            // ----- América Central (7) -----
            'Belize',
            'Costa Rica',
            'El Salvador',
            'Guatemala',
            'Honduras',
            'Nicaragua',
            'Panama',

            // ----- El Caribe (18) -----
            'Antigua and Barbuda',
            'Aruba',
            'Bahamas',
            'Barbados',
            'Cayman Islands',
            'Cuba',
            'Dominica',
            'Dominican Republic',
            'Grenada',
            'Haiti',
            'Jamaica',
            'Puerto Rico',
            'Saint Kitts and Nevis',
            'Saint Lucia',
            'Saint Vincent and the Grenadines',
            'Trinidad and Tobago',
            'Virgin Islands, British',
            'Virgin Islands, U.S.',

            // ----- América del Sur (12) -----
            'Argentina',
            'Bolivia',
            'Brazil',
            'Chile',
            'Colombia',
            'Ecuador',
            'Guyana',
            'Paraguay',
            'Peru',
            'Suriname',
            'Uruguay',
            'Venezuela',

            // ----- Asia (45) -----
            'Afghanistan',
            'Bahrain',
            'Bangladesh',
            'Bhutan',
            'Brunei Darussalam',
            'Cambodia',
            'China, People\'s Republic of',
            'Chinese Taipei',
            'Hong Kong, China',
            'India',
            'Indonesia',
            'Iran, Islamic Republic of',
            'Iraq',
            'Israel',
            'Japan',
            'Jordan',
            'Kazakhstan',
            'Korea, Democratic People\'s Republic of',
            'Korea, Republic of',
            'Kuwait',
            'Kyrgyzstan',
            'Lao People\'s Democratic Republic',
            'Lebanon',
            'Malaysia',
            'Maldives',
            'Mongolia',
            'Myanmar',
            'Nepal',
            'Oman',
            'Pakistan',
            'Palestine',
            'Philippines',
            'Qatar',
            'Saudi Arabia',
            'Singapore',
            'Sri Lanka',
            'Syrian Arab Republic',
            'Tajikistan',
            'Thailand',
            'Timor-Leste',
            'Turkmenistan',
            'United Arab Emirates',
            'Uzbekistan',
            'Vietnam',
            'Yemen',

            // ----- Europa (49) -----
            'Albania',
            'Andorra',
            'Armenia',
            'Austria',
            'Azerbaijan',
            'Belarus',
            'Belgium',
            'Bosnia and Herzegovina',
            'Bulgaria',
            'Croatia',
            'Cyprus',
            'Czechia',
            'Denmark',
            'Estonia',
            'Finland',
            'France',
            'Georgia',
            'Germany',
            'Great Britain',
            'Greece',
            'Hungary',
            'Iceland',
            'Ireland',
            'Italy',
            'Kosovo',
            'Latvia',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Malta',
            'Moldova, Republic of',
            'Monaco',
            'Montenegro',
            'Netherlands',
            'North Macedonia',
            'Norway',
            'Poland',
            'Portugal',
            'Romania',
            'Russian Federation',
            'San Marino',
            'Serbia',
            'Slovakia',
            'Slovenia',
            'Spain',
            'Sweden',
            'Switzerland',
            'Türkiye',
            'Ukraine',

            // ----- Oceanía (17) -----
            'American Samoa',
            'Australia',
            'Cook Islands',
            'Fiji',
            'Guam',
            'Kiribati',
            'Marshall Islands',
            'Micronesia, Federated States of',
            'Nauru',
            'New Zealand',
            'Palau',
            'Papua New Guinea',
            'Samoa',
            'Solomon Islands',
            'Tonga',
            'Tuvalu',
            'Vanuatu',

            // ----- Equipo especial (1) -----
            'Hope',
        ];

        foreach ($countries as $country) {
            Team::create([
                'name' => $country,
                'current_service_status' => 'NOT_HELPED',
            ]);
        }
    }
}
